//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHitCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHitCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 1a &lt;_main+0x1a&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingEventLog {
            get {
                return ResourceManager.GetString("EldenRingEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///Abductor Virgins,16000860
        ///&quot;Adan, Thief of Fire&quot;,1038410800
        ///&quot;Alecto, Black Knife Ringleader&quot;,1033420800
        ///Ancestor Spirit,12080800
        ///Ancient Dragon Lansseax,1041520800
        ///Ancient Hero of Zamor (Sainted Hero&apos;s Grave),30080800
        ///Ancient Hero of Zamor (Giant-Conquering Hero&apos;s Grave),30170800
        ///Ancient Hero of Zamor (Weeping Evergaol),1042330800
        ///&quot;Astel, Naturalborn of the Void&quot;,12040800
        ///&quot;Astel, Stars of Darkness&quot;,32110800
        ///Battlemage Hugues,1049390850
        ///Beastman of Farum Azula,31030800
        ///Beastman [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingEvents {
            get {
                return ResourceManager.GetString("EldenRingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 44 24 30 01          mov    BYTE PTR [rsp+0x30],0x1
        ///50                      push   rax
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 8b 81 08 e5 01 00    mov    rax,QWORD PTR [rcx+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///4c 3b 38                cmp    r15,QWORD PTR [rax]
        ///74 38                   je     59 &lt;validate_fall&gt;
        ///48 8b 80 e8 00 00 00    mov    rax,QWORD PTR [rax+0xe8]
        ///48 8b 40 10             mov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingFallDamage {
            get {
                return ResourceManager.GetString("EldenRingFallDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///50                      push   rax
        ///52                      push   rdx
        ///53                      push   rbx
        ///48 8b 15 00 00 00 00    mov    rdx,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 8b 82 08 e5 01 00    mov    rax,QWORD PTR [rdx+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 3b 88 98 00 00 00    cmp    rcx,QWORD PTR [rax+0x98]
        ///74 3f                   je     65 &lt;validate_hit&gt;
        ///48 8b 80 e8 00 00 00    mov    rax,QWORD PTR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingHit {
            get {
                return ResourceManager.GetString("EldenRingHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 44 24 28 01          mov    BYTE PTR [rsp+0x28],0x1
        ///50                      push   rax
        ///51                      push   rcx
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 8b 88 08 e5 01 00    mov    rcx,QWORD PTR [rax+0x1e508]
        ///48 8b 81 90 01 00 00    mov    rax,QWORD PTR [rcx+0x190]
        ///48 3b 58 70             cmp    rbx,QWORD PTR [rax+0x70]
        ///75 25                   jne    47 &lt;skip&gt;
        ///52                      push   rdx
        ///ba c2 10 00 00          mov    edx,0x10c2
        ///48 8b 89  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingKillBox {
            get {
                return ResourceManager.GetString("EldenRingKillBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 9 &lt;_main+0x9&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04             mov    BYTE PTR [rbx+0x4],r8b
        ///ff c7                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarEventLog {
            get {
                return ResourceManager.GetString("ScholarEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///The Last Giant,100971
        ///The Pursuer,100968
        ///Dragonrider,100959
        ///Old Dragonslayer,100960
        ///Flexile Sentry,100961
        ///Ruin Sentinels,100962
        ///The Lost Sinner,100963
        ///Belfry Gargoyles,101001
        ///Executioner&apos;s Chariot,100953
        ///Skeleton Lords,100954
        ///Covetous Demon,100955
        ///&quot;Mytha, the Baneful Queen&quot;,100956
        ///Red Smelter Demon,100964
        ///Old Iron King,100952
        ///Scorpioness Najka,100957
        ///Royal Rat Authority,100967
        ///Prowling Magus &amp; Congregation,101000
        ///The Duke&apos;s Dear Freja,100951
        ///Royal Rat Vanguard,100965
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarEvents {
            get {
                return ResourceManager.GetString("ScholarEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 39 99 d0 00 00 00    cmp    QWORD PTR [rcx+0xd0],rbx
        ///75 0a                   jne    1b &lt;normal&gt;
        ///85 c0                   test   eax,eax
        ///79 06                   jns    1b &lt;normal&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1b &lt;normal&gt;
        ///00000000001b &lt;normal&gt;:
        ///59                      pop    rcx
        ///89 83 68 01 00 00       mov    DWORD PTR [rbx+0x168],eax
        ///e9 00 00 00 00        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarFallDamage {
            get {
                return ResourceManager.GetString("ScholarFallDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 8b 89 d0 00 00 00    mov    rcx,QWORD PTR [rcx+0xd0]
        ///48 3b 4f 08             cmp    rcx,QWORD PTR [rdi+0x8]
        ///75 28                   jne    3d &lt;normal&gt;
        ///48 3b 4d f8             cmp    rcx,QWORD PTR [rbp-0x8]
        ///74 22                   je     3d &lt;normal&gt;
        ///83 bd 88 00 00 00 00    cmp    DWORD PTR [rbp+0x88],0x0
        ///74 13                   je     37 &lt;count_hit&gt;
        ///81 7c 24 48 07 c6 eb    cmp    DWORD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarHit {
            get {
                return ResourceManager.GetString("ScholarHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 87 60 13 00 00    mov    QWORD PTR [rdi+0x1360],rax
        ///c7 05 00 00 00 00 03    mov    DWORD PTR [rip+0x0],0x3        # 11 &lt;_main+0x11&gt;
        ///00 00 00
        ///e9 00 00 00 00          jmp    16 &lt;_main+0x16&gt;.
        /// </summary>
        internal static string ScholarIgtLoadGame {
            get {
                return ResourceManager.GetString("ScholarIgtLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 83 60 13 00 00    mov    QWORD PTR [rbx+0x1360],rax
        ///c7 05 00 00 00 00 01    mov    DWORD PTR [rip+0x0],0x1        # 11 &lt;_main+0x11&gt;
        ///00 00 00
        ///e9 00 00 00 00          jmp    16 &lt;_main+0x16&gt;.
        /// </summary>
        internal static string ScholarIgtNewGame {
            get {
                return ResourceManager.GetString("ScholarIgtNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e8 00 00 00 00          call   5 &lt;_main+0x5&gt;
        ///c7 05 00 00 00 00 02    mov    DWORD PTR [rip+0x0],0x2        # f &lt;_main+0xf&gt;
        ///00 00 00
        ///e9 00 00 00 00          jmp    14 &lt;_main+0x14&gt;.
        /// </summary>
        internal static string ScholarIgtStop {
            get {
                return ResourceManager.GetString("ScholarIgtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4c 8b 01                mov    r8,QWORD PTR [rcx]
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///4c 3b 81 d0 00 00 00    cmp    r8,QWORD PTR [rcx+0xd0]
        ///75 0a                   jne    1e &lt;exit&gt;
        ///85 d2                   test   edx,edx
        ///75 06                   jne    1e &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1e &lt;exit&gt;
        ///00000000001e &lt;exit&gt;:
        ///59                      pop    rcx
        ///89 54 24 10             mov    DWORD  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarKillBox {
            get {
                return ResourceManager.GetString("ScholarKillBox", resourceCulture);
            }
        }
    }
}
